networks:
  red: {}

services:
  app-cliente:
    image: jglete/inetum-cliente
    networks:
      - red
    depends_on:
      - app
    ports:
      - 80:80
  app:
    image: jglete/inetum
    networks:
      - red
    depends_on:
      - app_db
    ports:
      - 8081:8081

  app_db:
    image: mysql
    networks:
      - red
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=inetum